### ISSUE TITLE
支持.netframework3.5下使用

### ISSUE THREAD

**Issue by xiekun1992** [daixian/DNET#2]
亲，能弄个.netframework3.5版本的吗，我这边工程需要做兼容，最多用到.net3.5
![image](https://user-images.githubusercontent.com/10451769/57899012-e3423680-788d-11e9-9dba-5d1e53362cd3.png)

**Comment by daixian** [comment]
这个库就是.net3.5的呀。。。

**Comment by xiekun1992** [comment]
好的，我看到了，我去重新生成下
![image](https://user-images.githubusercontent.com/10451769/57899622-5cdb2400-7890-11e9-86b0-a8edba4c0154.png)
